### ISSUE TITLE
Support for Opera

### ISSUE THREAD

**Issue by rich-clark** [GoogleChromeLabs/uach-retrofill#10]
## Expected Behavior

Since Opera is Chromium-based, and provides support for UA-CH, the retrofill should generate a UA string that matches the browser, for example: 

```
navigator.userAgent == Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.329
```

## Actual Behavior

The retrofill generates a UA string indistinguishable from that of Chrome, and not matching `navigator.userAgent`:

```
navigator.userAgent == Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```

## Steps to Reproduce the Problem

1. Run https://googlechromelabs.github.io/uach-retrofill/demo.html on Opera. 

## Specifications

- Version: OPR/73.0.3856.329
- Platform: Mac OS X 10.15.7

**Comment by bvattikonda** [comment]
Does Opera send the full version number as part of Sec-CH-UA? If not, getting OPR/73.0.3856.329 in the UA would not be possible.

**Comment by rich-clark** [comment]
Ah, you are that that it's not possible to access the full version. Even so, it seems like you can get the major version from the brand in platforms. It's not possible to generate the full UA string, but you could at least generate something a bit more similar:

```
navigator.userAgent == Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73
```

Note that Edge has the same problem.

**Comment by bvattikonda** [comment]
+1 to your recommendation for adding `OPR/73` like string to the generated UA. And yes, Edge has the same problem.

**Comment by miketaylr** [comment]
It seems like Opera has disabled UA-CH since this issue was filed.

**Comment by miketaylr** [comment]
> It seems like Opera has disabled UA-CH since this issue was filed.

As of Opera 88, it seems like UA-CH is entirely supported - they even send Opera in the brand list, with the correct version.
<img width="632" alt="Screen Shot 2022-06-27 at 5 50 08 PM" src="https://user-images.githubusercontent.com/67283/176041764-01857415-814f-4f52-acdb-a4f380b6170d.png">

**Comment by miketaylr** [comment]
Let's close this in favor of #31 (even though this was opened first!)
