### ISSUE TITLE
Incorrect UA on Chromium OS

### ISSUE THREAD

**Issue by rich-clark** [GoogleChromeLabs/uach-retrofill#15]
## Expected Behavior

For a device with the platform `Chromium OS`, it is expected that the synthesized UA string contains "X11; CrOS", as it does for the platform `Chrome OS`. For example, on a particular UA, this is the native UA string:

```
Mozilla/5.0 (X11; CrOS x86_64 13597.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.90 Safari/537.36
```

## Actual Behavior

If the brand is `Chromium OS`, in the synthesized UA string, the platform as `Linux`. For the same UA as above, for example, this is the synthesized UA string:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.90 Safari/537.36
```

## Steps to Reproduce the Problem

I don't have access to a Chromium OS machine, but this behavior can be replicated by manually changing the value of platform to `Chromium OS`.

## Specifications

- Version:
- Platform:

**Comment by miketaylr** [comment]
This should be pretty simple to fix.
