### ISSUE TITLE
Retrofill UA only if the user agent is Chrome

### ISSUE THREAD

**Issue by bvattikonda** [GoogleChromeLabs/uach-retrofill#16]
## Actual Behavior
Several [bots / spiders](https://www.iab.com/guidelines/iab-abc-international-spiders-bots-list/) likely use Chromium based browsers for automated web requests. Such agents right now identify themselves by modifying the User-Agent header. When client hints are introduced and a client side JS adopts uach-retrofill the automated requests from such user agents will contain Chrome User-Agent instead of the UA string of the bot / spider.

## Expected Behavior
Websites should continue to be able to identify bots using User-Agent even after using uach-retrofill.

## Suggested Change
Verify that `navigator.userAgent` identifies itself as Chrome before filling `navigator.userAgent` with a string constructed from client hints.

**Comment by miketaylr** [comment]
This won't be bulletproof, because bots can be clever, but it does make sense at least until more browsers are shipping this API.

**Comment by bvattikonda** [comment]
I was not thinking of malicious bots when referring to bots. I was referring to well behaved bots which identify themselves accurately by setting the User-Agent header.

https://www.iab.com/guidelines/iab-abc-international-spiders-bots-list/ provides the list of such bots.
