### ISSUE TITLE
Provide standalone synthesis function

### ISSUE THREAD

**Issue by rich-clark** [GoogleChromeLabs/uach-retrofill#2]
We would like to run an experiment using this retrofill, but would like more control over how `navigator.userAgent`  is updated. More specifically, in addition to retrofilling the `userAgent` string, we also want to track how frequently `navigator.userAgent` is accessed, and whether it is accessed before the retrofill's Promise has resolved.

Would it be possible to either replace the existing `OverrideUserAgentUsingClientHints` function entirely or add an additional function that could be used to synthesize a UA string without actually modifying `navigator.userAgent`? Something like this would be perfect:

```js
/**
* @param {string[]} hints
* @return {Promise<string|undefined>} A Promise that resolves to a string if 
*     a UA could be synthesized from client hints, otherwise undefined.
*/
export async function getUserAgentUsingClientHints(hints) {
  // ...  
}
```

Anyone who wished to simply update `navigator.userAgent` could easily do so using this function:

```js
import {getUserAgentUsingClientHints} from 'uarch-retrofill';

getUserAgentUsingClientHints([""]).then((userAgent) => {
  if (userAgent) { 
      Object.defineProperty(navigator, 'userAgent', {
        value: userAgent,
        writable: false
      });
  }
});
```

**Comment by rowan-m** [comment]
I'll separate out the string generation and the override in a separate function with this signature.

**Comment by miketaylr** [comment]
You can probably address #1 at the same time by tossing the following into a demo.html (which can include a `<script type=module src=uach-retrofill.js><script>` (if you made it an ES module, etc).

```
OverrideUserAgentUsingClientHints([""]).then(() => {
  document.getElementById("output").innerHTML = navigator.userAgent;
})
```
