### ISSUE TITLE
Drop the restriction which creates synthetic UA only until end of 2021

### ISSUE THREAD

**Issue by bvattikonda** [GoogleChromeLabs/uach-retrofill#41]
The [restriction](https://github.com/GoogleChromeLabs/uach-retrofill/blob/fa026038375c6eeb5b3bee8b4b3ce88594d83303/uach-retrofill.js#L103) in the retrofill code means that retrofill is not created after 1640995199 timestamp. This maps to end of 2021. It would be good to remove this restriction so that the retrofill API can be used for the foreseeable future.

**Comment by miketaylr** [comment]
Yeah, not sure what the original intent was (perhaps "migrate your code, don't rely on this forever").
