### ISSUE TITLE
Retrofill for MS Edge 

### ISSUE THREAD

**Issue by bvattikonda** [GoogleChromeLabs/uach-retrofill#5]
## Expected Behavior
Typical Edge User-Agent header looks like:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43
```

## Actual Behavior
For the same browser, polyfill would return a string that looks like:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Edg/79.0.3945.74 Safari/537.36
```
Note the placement of Edg/x.x.x.x version number. In the User-Agent header it is after Safari/537.36 but polyfill places it before Safari.

## Request
Add `Edg/version` part of the UA string before Safari/537.36

**Comment by miketaylr** [comment]
> Add `Edg/version` part of the UA string before Safari/537.36

@bvattikonda just to clarify, you mean *after* `Safari/537.36`, correct?

**Comment by bvattikonda** [comment]
Yes. Sorry for the typo.

**Comment by miketaylr** [comment]
I'm not able to reproduce, which matches what my intuition would have been based on looking at the code where `Edg` is added:

https://github.com/GoogleChromeLabs/uach-retrofill/blob/e66bac5b2f79380a06dcc0a22b72316d2f15bfaa/uach-retrofill.js#L126-L132

![Screen Shot 2021-01-08 at 1 17 02 PM](https://user-images.githubusercontent.com/67283/104055280-1bf5f880-51b4-11eb-8f44-aaad1c0bab29.png)

@bvattikonda can you provide more details on how to reproduce the issue? I'm on macOS, using `Edge Version 87.0.664.75 (Official build) (64-bit)`, with the Experimental Web Platform Features flag enabled. Thanks.

**Comment by bvattikonda** [comment]
This actually looks good to me. My bad, I should have looked at the latest code here.

**Comment by miketaylr** [comment]
All good!
