### ISSUE TITLE
Investigate behavior of "architecture" checkbox on demo.html

### ISSUE THREAD

**Issue by miketaylr** [GoogleChromeLabs/uach-retrofill#8]
Investigate behavior of "architecture" checkbox on demo.html:

See https://github.com/GoogleChromeLabs/uach-retrofill/pull/7#pullrequestreview-564648073

I suspect the demo isn't broken, but possibly the architecture handling in the retrofill. 

I would expect clicking 'architecture' with the following UA:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.0.0 Safari/537.36 Edg/87.0.0.0`

would result in something that says "Intel".

**Comment by rowan-m** [comment]
I think this is actually a UA-CH implementation thing. On a Windows machine with  an Intel i7 looking at https://user-agent-client-hints.glitch.me/javascript.html I see:

```
> console.log(navigator.userAgent);
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

> navigator.userAgentData
.getHighEntropyValues(["architecture", "model", "platform", "platformVersion", "uaFullVersion"])
.then(ua => { console.log(ua) });
{
  "architecture": "x86",
  "model": "",
  "platform": "Windows",
  "platformVersion": "10.0",
  "uaFullVersion": "87.0.4280.141"
}
```

I don't think `architecture` is intended to be more granular than that.

**Comment by rowan-m** [comment]
I've also updated to show the original User-Agent value for easier comparison with the generated string.

**Comment by miketaylr** [comment]
Thanks for looking into this -- I think you're probably right. Just a limitation of the differences between models (which probably has very little real-world use).
