### ISSUE TITLE
Host demo.html on gh-pages and link to it from README.md

### ISSUE THREAD

**Issue by miketaylr** [GoogleChromeLabs/uach-retrofill#9]
That would be nice.

**Comment by rowan-m** [comment]
Clicked the Pages button. Will get README updated too.
https://googlechromelabs.github.io/uach-retrofill/demo.html

**Comment by miketaylr** [comment]
Nice!

**Comment by miketaylr** [comment]
I added a link to the description, that's probably good enough? 

<img width="393" alt="Screen Shot 2022-06-27 at 5 51 01 PM" src="https://user-images.githubusercontent.com/67283/176041858-b6e4bccd-c293-4a32-a39f-17d5e5d39c5f.png">
